export function isValidVerseReference(reference) {
  const bookAliases = {
    Genesis: [
      "Gen",
      "Gn",
      "Gensis",
      "Genisis",
      "Gennesis",
      "Geneses",
      "Gennisis",
      "Genesiss",
      "Ginisis",
      "Jenesis",
      "Jeneses",
      "Genes",
      "Geness",
      "Genezis",
      "Genezes",
    ],
    Exodus: [
      "Ex",
      "Exod",
      "Exdus",
      "Exodus",
      "Exouds",
      "Exoudus",
      "Exoduss",
      "Exoodus",
      "Exodis",
      "Exadas",
      "Exedus",
      "Exedes",
      "Exoudas",
      "Exzodus",
      "Exzodas",
    ],
    Leviticus: [
      "Lev",
      "Lv",
      "Levitcus",
      "Leviticuss",
      "Levitikus",
      "Levitikas",
      "Leviticis",
      "Leveticus",
      "Leviticuz",
      "Leviticis",
      "Levitecus",
      "Levitekis",
      "Levitocus",
      "Levaticus",
      "Levitic",
    ],
    Numbers: [
      "Num",
      "Nm",
      "Nmbrs",
      "Numb",
      "Nuumbers",
      "Numbbers",
      "Numbars",
      "Nummbers",
      "Nummers",
      "Nuummbers",
      "Numbirs",
      "Numbarz",
      "Numbahs",
      "Nummies",
      "Numz",
    ],
    Deuteronomy: [
      "Deut",
      "Dt",
      "Duteronomy",
      "Deutronomy",
      "Duteranomy",
      "Deuteronmy",
      "Dewteronomy",
      "Dewtronome",
      "Duteronomi",
      "Duteronamy",
      "Duteronomee",
      "Duteronumy",
      "Duteronumee",
      "Duteronumy",
      "Duteronome",
    ],
    Joshua: [
      "Josh",
      "Js",
      "Jshua",
      "Joshu",
      "Johsua",
      "Josha",
      "Josuha",
      "Jashua",
      "Jashuah",
      "Joshoa",
      "Jashwa",
      "Jashuwa",
      "Jash",
      "Jsh",
      "Jshu",
    ],
    Judges: [
      "Judg",
      "Jdg",
      "Jdgs",
      "Judge",
      "Judges",
      "Juddges",
      "Jugdes",
      "Jugdge",
      "Jugeds",
      "Jugdges",
      "Jugdg",
      "Jugdgz",
      "Jugedz",
      "Juged",
      "Jugdgis",
    ],
    Ruth: [
      "Rth",
      "Rt",
      "Ruth",
      "Rooth",
      "Rut",
      "Ruthe",
      "Rooth",
      "Roothie",
      "Ruthe",
      "Ruthee",
      "Roothy",
      "Rutthy",
      "Ruthy",
      "Rutthy",
      "Rutthie",
    ],
    "1 Samuel": [
      "1 Sam",
      "1Sam",
      "1 Sm",
      "1Sm",
      "1Samuel",
      "1Sammuel",
      "1Sam",
      "1Sml",
      "1Samm",
      "1Sammu",
      "1Sammie",
      "1Sammu",
      "1Samu",
      "1Sammi",
      "1Sami",
      "1Samy",
      "1Samo",
    ],
    "2 Samuel": [
      "2 Sam",
      "2 Sm",
      "2Sm",
      "2Samuel",
      "2Sammuel",
      "2Sam",
      "2Sml",
      "2Samm",
      "2Sammu",
      "2Sammie",
      "2Sammu",
      "2Samu",
      "2Sammi",
      "2Sami",
      "2Samy",
      "2Samo",
    ],
    "1 Kings": [
      "1 Kgs",
      "1Kgs",
      "1 Ki",
      "1Ki",
      "1Kings",
      "1King",
      "1Kngs",
      "1Kng",
      "1Kgs",
      "1Kis",
      "1Kngz",
      "1Kinz",
      "1Kinzg",
      "1Kinzgs",
      "1Kingsz",
      "1Kingsy",
      "1Kingsx",
    ],
    "2 Kings": [
      "2 Kgs",
      "2Kgs",
      "2 Ki",
      "2Ki",
      "2Kings",
      "2King",
      "2Kngs",
      "2Kng",
      "2Kgs",
      "2Kis",
      "2Kngz",
      "2Kinz",
      "2Kinzg",
      "2Kinzgs",
      "2Kingsz",
      "2Kingsy",
      "2Kingsx",
    ],
    "1 Chronicles": [
      "1 Chr",
      "1Chr",
      "1 Ch",
      "1Ch",
      "1Chron",
      "1Chronicles",
      "1Cron",
      "1Cronicles",
      "1Chrn",
      "1Chrncls",
      "1Chro",
      "1Chrncl",
      "1Chrnicle",
      "1Chronic",
      "1Chrncls",
      "1Chrnclz",
      "1Chrncl",
    ],
    "2 Chronicles": [
      "2 Chr",
      "2Chr",
      "2 Ch",
      "2Ch",
      "2Chron",
      "2Chronicles",
      "2Cron",
      "2Cronicles",
      "2Chrn",
      "2Chrncls",
      "2Chro",
      "2Chrncl",
      "2Chrnicle",
      "2Chronic",
      "2Chrncls",
      "2Chrnclz",
      "2Chrncl",
    ],
    Ezra: [
      "Ezr",
      "Ezraa",
      "Ezrah",
      "Ezrra",
      "Ezrrah",
      "Ezraah",
      "Ezrr",
      "Ezr",
      "Ezrae",
      "Ezraee",
      "Ezraah",
      "Ezraar",
      "Ezrao",
      "Ezrau",
      "Ezrai",
    ],
    Nehemiah: [
      "Neh",
      "Ne",
      "Nehmiah",
      "Nehemiah",
      "Nehemia",
      "Nehemah",
      "Nehemaih",
      "Nehemaya",
      "Nehemiyah",
      "Nehemija",
      "Nehemias",
      "Nehemiyas",
      "Nehemiyah",
      "Nehemijah",
      "Nehemiy",
    ],
    Esther: [
      "Est",
      "Es",
      "Ester",
      "Esther",
      "Esthr",
      "Esth",
      "Estha",
      "Esthur",
      "Estherr",
      "Esthers",
      "Esthre",
      "Esthree",
      "Esthur",
      "Esthurr",
      "Esthura",
    ],
    Job: [
      "Jb",
      "Jobe",
      "Jobb",
      "Jobbe",
      "Jobi",
      "Jobie",
      "Joby",
      "Jobey",
      "Jobee",
      "Jobo",
      "Jobu",
      "Joba",
      "Jobay",
      "Jobae",
      "Jobai",
    ],
    Psalms: [
      "Ps",
      "Psa",
      "Psalm",
      "Pslm",
      "Pslms",
      "Psalmz",
      "Pslmz",
      "Psalms",
      "Psalmez",
      "Psalmsz",
      "Psalmsa",
      "Psalmsi",
      "Psalmsu",
      "Psalmsy",
      "Psalmsx",
    ],
    Proverbs: [
      "Prov",
      "Pr",
      "Provrbs",
      "Provrb",
      "Provrbe",
      "Provrbs",
      "Provrbz",
      "Proverbe",
      "Proverbes",
      "Proverbez",
      "Proverbee",
      "Proverbi",
      "Proverbo",
      "Proverbu",
      "Proverba",
    ],
    Ecclesiastes: [
      "Ecc",
      "Eccl",
      "Ecclestes",
      "Ecclests",
      "Ecclests",
      "Ecclestez",
      "Ecclests",
      "Eccleste",
      "Ecclesta",
      "Ecclesto",
      "Ecclesti",
      "Ecclestee",
      "Ecclestea",
      "Ecclestu",
      "Ecclesty",
    ],
    "Song of Solomon": [
      "Song",
      "Sg",
      "Sos",
      "Solomon",
      "Solomn",
      "Solomun",
      "Solomom",
      "Solomont",
      "Solomoni",
      "Solomonu",
      "Solomono",
      "Solomona",
      "Solomonaa",
      "Solomonee",
      "Solomonii",
      "Solomonoo",
    ],
    Isaiah: [
      "Isa",
      "Is",
      "Isiah",
      "Isaia",
      "Isaiahh",
      "Isayah",
      "Isayha",
      "Isaaha",
      "Isiaha",
      "Isiaiah",
      "Isaie",
      "Isaio",
      "Isaiu",
      "Isaiaa",
      "Isaiai",
    ],
    Jeremiah: [
      "Jer",
      "Je",
      "Jerimiah",
      "Jeremia",
      "Jeremah",
      "Jeremaih",
      "Jeremaya",
      "Jeremiyah",
      "Jeremija",
      "Jeremias",
      "Jeremiyas",
      "Jeremiyah",
      "Jeremijah",
      "Jeremiy",
      "Jeremai",
    ],
    Lamentations: [
      "Lam",
      "La",
      "Lament",
      "Lamentation",
      "Lamentatn",
      "Lamenttns",
      "Lamenttn",
      "Lamentat",
      "Lamentatz",
      "Lamentatzn",
      "Lamentatzns",
      "Lamentatn",
      "Lamenttn",
      "Lamentats",
      "Lamentatz",
    ],
    Ezekiel: [
      "Ezek",
      "Ez",
      "Ezeikel",
      "Ezekeil",
      "Ezekeal",
      "Ezekeul",
      "Ezekeol",
      "Ezekeil",
      "Ezekeill",
      "Ezekeila",
      "Ezekeile",
      "Ezekeili",
      "Ezekeilo",
      "Ezekeilu",
      "Ezekeily",
    ],
    Daniel: [
      "Dan",
      "Dn",
      "Daneil",
      "Danie",
      "Daneel",
      "Daneal",
      "Daneul",
      "Daneol",
      "Daneill",
      "Daniell",
      "Daniele",
      "Danielee",
      "Danielei",
      "Danieleo",
      "Danieleu",
    ],
    Hosea: [
      "Hos",
      "Ho",
      "Hose",
      "Hosee",
      "Hosei",
      "Hoseo",
      "Hoseu",
      "Hosey",
      "Hoseya",
      "Hoseyah",
      "Hoseia",
      "Hoseeah",
      "Hoseeah",
      "Hoseeah",
      "Hoseia",
    ],
    Joel: [
      "Jl",
      "Joell",
      "Joelle",
      "Joel",
      "Joell",
      "Joellee",
      "Joellei",
      "Joelleo",
      "Joelleu",
      "Joellea",
      "Joellie",
      "Joellio",
      "Joelliu",
      "Joellia",
      "Joelliee",
    ],
    Amos: [
      "Am",
      "Ams",
      "Amoss",
      "Amos",
      "Amose",
      "Amosi",
      "Amoso",
      "Amosu",
      "Amosa",
      "Amosee",
      "Amosei",
      "Amoseo",
      "Amoseu",
      "Amosea",
      "Amosie",
    ],
    Obadiah: [
      "Obad",
      "Ob",
      "Obdiah",
      "Obadia",
      "Obadiah",
      "Obadyah",
      "Obadya",
      "Obadeah",
      "Obadea",
      "Obadee",
      "Obadei",
      "Obadeo",
      "Obadeu",
      "Obadeah",
      "Obadeia",
    ],
    Jonah: [
      "Jon",
      "Jnh",
      "Jona",
      "Jonah",
      "Jonaa",
      "Jonae",
      "Jonai",
      "Jonao",
      "Jonau",
      "Jonaah",
      "Jonae",
      "Jonaei",
      "Jonaeo",
      "Jonaeu",
      "Jonaea",
    ],
    Micah: [
      "Mic",
      "Mi",
      "Mica",
      "Micah",
      "Mikah",
      "Micaa",
      "Micae",
      "Micaei",
      "Micaeo",
      "Micaeu",
      "Micaea",
      "Micahh",
      "Micahs",
      "Micahz",
      "Micahx",
    ],
    Nahum: [
      "Nah",
      "Na",
      "Nahm",
      "Nahum",
      "Nahumm",
      "Nahuum",
      "Nahumm",
      "Nahom",
      "Nahom",
      "Nahoum",
      "Nahume",
      "Nahumi",
      "Nahumo",
      "Nahumu",
      "Nahuma",
    ],
    Habakkuk: [
      "Hab",
      "Hb",
      "Habakuk",
      "Habakkuk",
      "Habakukk",
      "Habakk",
      "Habak",
      "Habaku",
      "Habakku",
      "Habakke",
      "Habakki",
      "Habakko",
      "Habakku",
      "Habakka",
      "Habakks",
    ],
    Zephaniah: [
      "Zeph",
      "Zp",
      "Zephan",
      "Zepaniah",
      "Zephanah",
      "Zephanaih",
      "Zephanaya",
      "Zephanayah",
      "Zephanija",
      "Zephanias",
      "Zephaniaz",
      "Zephanix",
      "Zephanic",
      "Zephanis",
      "Zephanit",
    ],
    Haggai: [
      "Hag",
      "Hg",
      "Hagg",
      "Haggai",
      "Haggie",
      "Haggae",
      "Haggay",
      "Haggaa",
      "Haggae",
      "Haggai",
      "Haggao",
      "Haggau",
      "Hagga",
      "Haggah",
      "Haggan",
    ],
    Zechariah: [
      "Zech",
      "Zc",
      "Zechar",
      "Zecharia",
      "Zechariah",
      "Zechariaa",
      "Zechariae",
      "Zechariai",
      "Zechariao",
      "Zechariau",
      "Zechariaah",
      "Zechariaeh",
      "Zechariaih",
      "Zechariaoh",
      "Zechariauh",
    ],
    Malachi: [
      "Mal",
      "Ml",
      "Malach",
      "Malachi",
      "Malachy",
      "Malachai",
      "Malachia",
      "Malachie",
      "Malachiu",
      "Malachio",
      "Malachia",
      "Malachiah",
      "Malachy",
      "Malachye",
      "Malachyi",
    ],
    Matthew: [
      "Matt",
      "Mt",
      "Mathew",
      "Matthu",
      "Mattho",
      "Matthu",
      "Matthw",
      "Matthwe",
      "Matthwi",
      "Matthwo",
      "Matthwu",
      "Matthwa",
      "Matthwah",
      "Matthweh",
      "Matthwee",
    ],
    Mark: [
      "Mk",
      "Mrk",
      "Markk",
      "Mark",
      "Marke",
      "Marki",
      "Marko",
      "Marku",
      "Marka",
      "Markah",
      "Markeh",
      "Markee",
      "Markei",
      "Markeo",
      "Markeu",
    ],
    Luke: [
      "Lk",
      "Lu",
      "Luk",
      "Luke",
      "Lukke",
      "Lukk",
      "Luk",
      "Lukie",
      "Lukio",
      "Lukiu",
      "Lukia",
      "Lukiah",
      "Lukieh",
      "Lukiee",
      "Lukiei",
    ],
    John: [
      "Jn",
      "Jo",
      "Joh",
      "John",
      "Jonn",
      "Jon",
      "Johne",
      "Johni",
      "Johno",
      "Johnu",
      "Johna",
      "Johnah",
      "Johneh",
      "Johnee",
      "Johnie",
    ],
    Acts: [
      "Ac",
      "Acts",
      "Act",
      "Actz",
      "Acts",
      "Actss",
      "Actz",
      "Actsz",
      "Actse",
      "Actsi",
      "Actso",
      "Actsu",
      "Actsa",
      "Actsah",
      "Actseh",
    ],
    Romans: [
      "Rom",
      "Ro",
      "Roms",
      "Roman",
      "Romans",
      "Romanss",
      "Romansz",
      "Romansx",
      "Romansc",
      "Romansv",
      "Romansb",
      "Romansn",
      "Romansm",
      "Romansl",
      "Romansk",
    ],
    "1 Corinthians": [
      "1 Cor",
      "1 Co",
      "1Co",
      "1Cor",
      "1Corinthians",
      "1Corin",
      "1Corinth",
      "1Corint",
      "1Corinthi",
      "1Corinthia",
      "1Corinthian",
      "1Corinthianss",
      "1Corinthiansz",
      "1Corinthiansx",
      "1Corinthiansc",
      "1Corinthiansv",
    ],
    "2 Corinthians": [
      "2 Cor",
      "2 Co",
      "2Co",
      "2Cor",
      "2Corinthians",
      "2Corin",
      "2Corinth",
      "2Corint",
      "2Corinthi",
      "2Corinthia",
      "2Corinthian",
      "2Corinthianss",
      "2Corinthiansz",
      "2Corinthiansx",
      "2Corinthiansc",
      "2Corinthiansv",
    ],
    Galatians: [
      "Gal",
      "Ga",
      "Gala",
      "Galat",
      "Galati",
      "Galatia",
      "Galatian",
      "Galatians",
      "Galatianss",
      "Galatiansz",
      "Galatiansx",
      "Galatiansc",
      "Galatiansv",
      "Galatiansb",
      "Galatiansn",
    ],
    Ephesians: [
      "Eph",
      "Ep",
      "Ephes",
      "Ephesi",
      "Ephesia",
      "Ephesian",
      "Ephesians",
      "Ephesianss",
      "Ephesiansz",
      "Ephesiansx",
      "Ephesiansc",
      "Ephesiansv",
      "Ephesiansb",
      "Ephesiansn",
      "Ephesiansm",
    ],
    Philippians: [
      "Phil",
      "Php",
      "Philip",
      "Philipp",
      "Philippi",
      "Philippia",
      "Philippian",
      "Philippians",
      "Philippianss",
      "Philippiansz",
      "Philippiansx",
      "Philippiansc",
      "Philippiansv",
      "Philippiansb",
      "Philippiansn",
    ],
    Colossians: [
      "Col",
      "Co",
      "Colo",
      "Colos",
      "Coloss",
      "Colossi",
      "Colossia",
      "Colossian",
      "Colossians",
      "Colossianss",
      "Colossiansz",
      "Colossiansx",
      "Colossiansc",
      "Colossiansv",
      "Colossiansb",
    ],
    "1 Thessalonians": [
      "1 Thess",
      "1Thess",
      "1Thes",
      "1Th",
      "1 Th",
      "1Thess",
      "1Thessalonians",
      "1Thessalon",
      "1Thes",
      "1Thessal",
      "1Thessa",
      "1Thess",
      "1Thes",
      "1Thessalonianss",
      "1Thessaloniansz",
      "1Thessaloniansx",
      "1Thessaloniansc",
      "1Thessaloniansv",
    ],
    "2 Thessalonians": [
      "2 Thess",
      "2 Thes",
      "2Th",
      "2 Th",
      "2Thess",
      "2Thessalonians",
      "2Thessalon",
      "2Thessalo",
      "2Thessal",
      "2Thessa",
      "2Thess",
      "2Thes",
      "2Thessalonianss",
      "2Thessaloniansz",
      "2Thessaloniansx",
      "2Thessaloniansc",
      "2Thessaloniansv",
    ],
    "1 Timothy": [
      "1 Tim",
      "1 Ti",
      "1Ti",
      "1Tim",
      "1Timothy",
      "1Timo",
      "1Timot",
      "1Timoth",
      "1Timothi",
      "1Timothie",
      "1Timothio",
      "1Timothiu",
      "1Timothia",
      "1Timothiah",
      "1Timothieh",
      "1Timothiee",
    ],
    "2 Timothy": [
      "2 Tim",
      "2 Ti",
      "2Ti",
      "2Tim",
      "2Timothy",
      "2Timo",
      "2Timot",
      "2Timoth",
      "2Timothi",
      "2Timothie",
      "2Timothio",
      "2Timothiu",
      "2Timothia",
      "2Timothiah",
      "2Timothieh",
      "2Timothiee",
    ],
    Titus: [
      "Tit",
      "Ti",
      "Tits",
      "Titu",
      "Titus",
      "Tituss",
      "Titusz",
      "Titusx",
      "Titusc",
      "Titusv",
      "Titusb",
      "Titusn",
      "Titusm",
      "Titusl",
      "Titusk",
    ],
    Philemon: [
      "Phlm",
      "Phm",
      "Phile",
      "Philem",
      "Philemo",
      "Philemon",
      "Philemonn",
      "Philemone",
      "Philemoni",
      "Philemono",
      "Philemonu",
      "Philemona",
      "Philemonah",
      "Philemoneh",
      "Philemonee",
    ],
    Hebrews: [
      "Heb",
      "Hb",
      "Hebr",
      "Hebre",
      "Hebrew",
      "Hebrews",
      "Hebrewss",
      "Hebrewsz",
      "Hebrewsx",
      "Hebrewsc",
      "Hebrewsv",
      "Hebrewsb",
      "Hebrewsn",
      "Hebrewsm",
      "Hebrewsl",
    ],
    James: [
      "Jas",
      "Ja",
      "Jame",
      "James",
      "Jamess",
      "Jamesz",
      "Jamesx",
      "Jamesc",
      "Jamesv",
      "Jamesb",
      "Jamesn",
      "Jamesm",
      "Jamesl",
      "Jamesk",
      "Jamesj",
    ],
    "1 Peter": [
      "1 Pet",
      "1 Pe",
      "1Pe",
      "1Peter",
      "1Petr",
      "1Pete",
      "1Pet",
      "1Peti",
      "1Peto",
      "1Petu",
      "1Peta",
      "1Petah",
      "1Pete",
      "1Petei",
      "1Peteo",
      "1Peteu",
    ],
    "2 Peter": [
      "2 Pet",
      "2 Pe",
      "2Pe",
      "2Peter",
      "2Petr",
      "2Pete",
      "2Pet",
      "2Peti",
      "2Peto",
      "2Petu",
      "2Peta",
      "2Petah",
      "2Pete",
      "2Petei",
      "2Peteo",
      "2Peteu",
    ],
    "1 John": [
      "1 Jn",
      "1Jn",
      "1 Jo",
      "1Jo",
      "1John",
      "1Joh",
      "1Jon",
      "1Jonn",
      "1Johne",
      "1Johni",
      "1Johno",
      "1Johnu",
      "1Johna",
      "1Johnah",
      "1Johneh",
      "1Johnee",
      "1Johnie",
    ],
    "2 John": [
      "2 Jn",
      "2Jn",
      "2 Jo",
      "2Jo",
      "2John",
      "2Joh",
      "2Jon",
      "2Jonn",
      "2Johne",
      "2Johni",
      "2Johno",
      "2Johnu",
      "2Johna",
      "2Johnah",
      "2Johneh",
      "2Johnee",
      "2Johnie",
    ],
    "3 John": [
      "3 Jn",
      "3Jn",
      "3 Jo",
      "3Jo",
      "3John",
      "3Joh",
      "3Jon",
      "3Jonn",
      "3Johne",
      "3Johni",
      "3Johno",
      "3Johnu",
      "3Johna",
      "3Johnah",
      "3Johneh",
      "3Johnee",
      "3Johnie",
    ],
    Jude: [
      "Jude",
      "Jd",
      "Jud",
      "Judee",
      "Judei",
      "Judeo",
      "Judeu",
      "Judea",
      "Judeah",
      "Judeh",
      "Judeee",
      "Judeei",
      "Judeeo",
      "Judeeu",
      "Judeea",
    ],
    Revelation: [
      "Rev",
      "Rv",
      "Revel",
      "Revela",
      "Revelat",
      "Revelati",
      "Revelatio",
      "Revelation",
      "Revelations",
      "Revelationz",
      "Revelationx",
      "Revelationc",
      "Revelationv",
      "Revelationb",
      "Revelationn",
    ],
  };

  const bibleStructure = {
    Genesis: {
      "1": "31",
      "2": "25",
      "3": "24",
      "4": "26",
      "5": "32",
      "6": "22",
      "7": "24",
      "8": "22",
      "9": "29",
      "10": "32",
      "11": "32",
      "12": "20",
      "13": "18",
      "14": "24",
      "15": "21",
      "16": "16",
      "17": "27",
      "18": "33",
      "19": "38",
      "20": "18",
      "21": "34",
      "22": "24",
      "23": "20",
      "24": "67",
      "25": "34",
      "26": "35",
      "27": "46",
      "28": "22",
      "29": "35",
      "30": "43",
      "31": "55",
      "32": "32",
      "33": "20",
      "34": "31",
      "35": "29",
      "36": "43",
      "37": "36",
      "38": "30",
      "39": "23",
      "40": "23",
      "41": "57",
      "42": "38",
      "43": "34",
      "44": "34",
      "45": "28",
      "46": "34",
      "47": "31",
      "48": "22",
      "49": "33",
      "50": "26",
    },
    Exodus: {
      "1": "22",
      "2": "25",
      "3": "22",
      "4": "31",
      "5": "23",
      "6": "30",
      "7": "25",
      "8": "32",
      "9": "35",
      "10": "29",
      "11": "10",
      "12": "51",
      "13": "22",
      "14": "31",
      "15": "27",
      "16": "36",
      "17": "16",
      "18": "27",
      "19": "25",
      "20": "26",
      "21": "36",
      "22": "31",
      "23": "33",
      "24": "18",
      "25": "40",
      "26": "37",
      "27": "21",
      "28": "43",
      "29": "46",
      "30": "38",
      "31": "18",
      "32": "35",
      "33": "23",
      "34": "35",
      "35": "35",
      "36": "38",
      "37": "29",
      "38": "31",
      "39": "43",
      "40": "38",
    },
    Leviticus: {
      "1": "17",
      "2": "16",
      "3": "17",
      "4": "35",
      "5": "19",
      "6": "30",
      "7": "38",
      "8": "36",
      "9": "24",
      "10": "20",
      "11": "47",
      "12": "8",
      "13": "59",
      "14": "57",
      "15": "33",
      "16": "34",
      "17": "16",
      "18": "30",
      "19": "37",
      "20": "27",
      "21": "24",
      "22": "33",
      "23": "44",
      "24": "23",
      "25": "55",
      "26": "46",
      "27": "34",
    },
    Numbers: {
      "1": "54",
      "2": "34",
      "3": "51",
      "4": "49",
      "5": "31",
      "6": "27",
      "7": "89",
      "8": "26",
      "9": "23",
      "10": "36",
      "11": "35",
      "12": "16",
      "13": "33",
      "14": "45",
      "15": "41",
      "16": "50",
      "17": "13",
      "18": "32",
      "19": "22",
      "20": "29",
      "21": "35",
      "22": "41",
      "23": "30",
      "24": "25",
      "25": "18",
      "26": "65",
      "27": "23",
      "28": "31",
      "29": "40",
      "30": "16",
      "31": "54",
      "32": "42",
      "33": "56",
      "34": "29",
      "35": "34",
      "36": "13",
    },
    Deuteronomy: {
      "1": "46",
      "2": "37",
      "3": "29",
      "4": "49",
      "5": "33",
      "6": "25",
      "7": "26",
      "8": "20",
      "9": "29",
      "10": "22",
      "11": "32",
      "12": "32",
      "13": "18",
      "14": "29",
      "15": "23",
      "16": "22",
      "17": "20",
      "18": "22",
      "19": "21",
      "20": "20",
      "21": "23",
      "22": "30",
      "23": "25",
      "24": "22",
      "25": "19",
      "26": "19",
      "27": "26",
      "28": "68",
      "29": "29",
      "30": "20",
      "31": "30",
      "32": "52",
      "33": "29",
      "34": "12",
    },
    Joshua: {
      "1": "18",
      "2": "24",
      "3": "17",
      "4": "24",
      "5": "15",
      "6": "27",
      "7": "26",
      "8": "35",
      "9": "27",
      "10": "43",
      "11": "23",
      "12": "24",
      "13": "33",
      "14": "15",
      "15": "63",
      "16": "10",
      "17": "18",
      "18": "28",
      "19": "51",
      "20": "9",
      "21": "45",
      "22": "34",
      "23": "16",
      "24": "33",
    },
    Judges: {
      "1": "36",
      "2": "23",
      "3": "31",
      "4": "24",
      "5": "31",
      "6": "40",
      "7": "25",
      "8": "35",
      "9": "57",
      "10": "18",
      "11": "40",
      "12": "15",
      "13": "25",
      "14": "20",
      "15": "20",
      "16": "31",
      "17": "13",
      "18": "31",
      "19": "30",
      "20": "48",
      "21": "25",
    },
    Ruth: {
      "1": "22",
      "2": "23",
      "3": "18",
      "4": "22",
    },
    "1 Samuel": {
      "1": "28",
      "2": "36",
      "3": "21",
      "4": "22",
      "5": "12",
      "6": "21",
      "7": "17",
      "8": "22",
      "9": "27",
      "10": "27",
      "11": "15",
      "12": "25",
      "13": "23",
      "14": "52",
      "15": "35",
      "16": "23",
      "17": "58",
      "18": "30",
      "19": "24",
      "20": "42",
      "21": "15",
      "22": "23",
      "23": "29",
      "24": "22",
      "25": "44",
      "26": "25",
      "27": "12",
      "28": "25",
      "29": "11",
      "30": "31",
      "31": "13",
    },
    "2 Samuel": {
      "1": "27",
      "2": "32",
      "3": "39",
      "4": "12",
      "5": "25",
      "6": "23",
      "7": "29",
      "8": "18",
      "9": "13",
      "10": "19",
      "11": "27",
      "12": "31",
      "13": "39",
      "14": "33",
      "15": "37",
      "16": "23",
      "17": "29",
      "18": "33",
      "19": "43",
      "20": "26",
      "21": "22",
      "22": "51",
      "23": "39",
      "24": "25",
    },
    "1 Kings": {
      "1": "53",
      "2": "46",
      "3": "28",
      "4": "34",
      "5": "18",
      "6": "38",
      "7": "51",
      "8": "66",
      "9": "28",
      "10": "29",
      "11": "43",
      "12": "33",
      "13": "34",
      "14": "31",
      "15": "34",
      "16": "34",
      "17": "24",
      "18": "46",
      "19": "21",
      "20": "43",
      "21": "29",
      "22": "53",
    },
    "2 Kings": {
      "1": "18",
      "2": "25",
      "3": "27",
      "4": "44",
      "5": "27",
      "6": "33",
      "7": "20",
      "8": "29",
      "9": "37",
      "10": "36",
      "11": "21",
      "12": "21",
      "13": "25",
      "14": "29",
      "15": "38",
      "16": "20",
      "17": "41",
      "18": "37",
      "19": "37",
      "20": "21",
      "21": "26",
      "22": "20",
      "23": "37",
      "24": "20",
      "25": "30",
    },
    "1 Chronicles": {
      "1": "54",
      "2": "55",
      "3": "24",
      "4": "43",
      "5": "26",
      "6": "81",
      "7": "40",
      "8": "40",
      "9": "44",
      "10": "14",
      "11": "47",
      "12": "40",
      "13": "14",
      "14": "17",
      "15": "29",
      "16": "43",
      "17": "27",
      "18": "17",
      "19": "19",
      "20": "8",
      "21": "30",
      "22": "19",
      "23": "32",
      "24": "31",
      "25": "31",
      "26": "32",
      "27": "34",
      "28": "21",
      "29": "30",
    },
    "2 Chronicles": {
      "1": "17",
      "2": "18",
      "3": "17",
      "4": "22",
      "5": "14",
      "6": "42",
      "7": "22",
      "8": "18",
      "9": "31",
      "10": "19",
      "11": "23",
      "12": "16",
      "13": "22",
      "14": "15",
      "15": "19",
      "16": "14",
      "17": "19",
      "18": "34",
      "19": "11",
      "20": "37",
      "21": "20",
      "22": "12",
      "23": "21",
      "24": "27",
      "25": "28",
      "26": "23",
      "27": "9",
      "28": "27",
      "29": "36",
      "30": "27",
      "31": "21",
      "32": "33",
      "33": "25",
      "34": "33",
      "35": "27",
      "36": "23",
    },
    Ezra: {
      "1": "11",
      "2": "70",
      "3": "13",
      "4": "24",
      "5": "17",
      "6": "22",
      "7": "28",
      "8": "36",
      "9": "15",
      "10": "44",
    },
    Nehemiah: {
      "1": "11",
      "2": "20",
      "3": "32",
      "4": "23",
      "5": "19",
      "6": "19",
      "7": "73",
      "8": "18",
      "9": "38",
      "10": "39",
      "11": "36",
      "12": "47",
      "13": "31",
    },
    Esther: {
      "1": "22",
      "2": "23",
      "3": "15",
      "4": "17",
      "5": "14",
      "6": "14",
      "7": "10",
      "8": "17",
      "9": "32",
      "10": "3",
    },
    Job: {
      "1": "22",
      "2": "13",
      "3": "26",
      "4": "21",
      "5": "27",
      "6": "30",
      "7": "21",
      "8": "22",
      "9": "35",
      "10": "22",
      "11": "20",
      "12": "25",
      "13": "28",
      "14": "22",
      "15": "35",
      "16": "22",
      "17": "16",
      "18": "21",
      "19": "29",
      "20": "29",
      "21": "34",
      "22": "30",
      "23": "17",
      "24": "25",
      "25": "6",
      "26": "14",
      "27": "23",
      "28": "28",
      "29": "25",
      "30": "31",
      "31": "40",
      "32": "22",
      "33": "33",
      "34": "37",
      "35": "16",
      "36": "33",
      "37": "24",
      "38": "41",
      "39": "30",
      "40": "24",
      "41": "34",
      "42": "17",
    },
    Psalm: {
      "1": "6",
      "2": "12",
      "3": "8",
      "4": "8",
      "5": "12",
      "6": "10",
      "7": "17",
      "8": "9",
      "9": "20",
      "10": "18",
      "11": "7",
      "12": "8",
      "13": "6",
      "14": "7",
      "15": "5",
      "16": "11",
      "17": "15",
      "18": "50",
      "19": "14",
      "20": "9",
      "21": "13",
      "22": "31",
      "23": "6",
      "24": "10",
      "25": "22",
      "26": "12",
      "27": "14",
      "28": "9",
      "29": "11",
      "30": "12",
      "31": "24",
      "32": "11",
      "33": "22",
      "34": "22",
      "35": "28",
      "36": "12",
      "37": "40",
      "38": "22",
      "39": "13",
      "40": "17",
      "41": "13",
      "42": "11",
      "43": "5",
      "44": "26",
      "45": "17",
      "46": "11",
      "47": "9",
      "48": "14",
      "49": "20",
      "50": "23",
      "51": "19",
      "52": "9",
      "53": "6",
      "54": "7",
      "55": "23",
      "56": "13",
      "57": "11",
      "58": "11",
      "59": "17",
      "60": "12",
      "61": "8",
      "62": "12",
      "63": "11",
      "64": "10",
      "65": "13",
      "66": "20",
      "67": "7",
      "68": "35",
      "69": "36",
      "70": "5",
      "71": "24",
      "72": "20",
      "73": "28",
      "74": "23",
      "75": "10",
      "76": "12",
      "77": "20",
      "78": "72",
      "79": "13",
      "80": "19",
      "81": "16",
      "82": "8",
      "83": "18",
      "84": "12",
      "85": "13",
      "86": "17",
      "87": "7",
      "88": "18",
      "89": "52",
      "90": "17",
      "91": "16",
      "92": "15",
      "93": "5",
      "94": "23",
      "95": "11",
      "96": "13",
      "97": "12",
      "98": "9",
      "99": "9",
      "100": "5",
      "101": "8",
      "102": "28",
      "103": "22",
      "104": "35",
      "105": "45",
      "106": "48",
      "107": "43",
      "108": "13",
      "109": "31",
      "110": "7",
      "111": "10",
      "112": "10",
      "113": "9",
      "114": "8",
      "115": "18",
      "116": "19",
      "117": "2",
      "118": "29",
      "119": "176",
      "120": "7",
      "121": "8",
      "122": "9",
      "123": "4",
      "124": "8",
      "125": "5",
      "126": "6",
      "127": "5",
      "128": "6",
      "129": "8",
      "130": "8",
      "131": "3",
      "132": "18",
      "133": "3",
      "134": "3",
      "135": "21",
      "136": "26",
      "137": "9",
      "138": "8",
      "139": "24",
      "140": "13",
      "141": "10",
      "142": "7",
      "143": "12",
      "144": "15",
      "145": "21",
      "146": "10",
      "147": "20",
      "148": "14",
      "149": "9",
      "150": "6",
    },
    Proverbs: {
      "1": "33",
      "2": "22",
      "3": "35",
      "4": "27",
      "5": "23",
      "6": "35",
      "7": "27",
      "8": "36",
      "9": "18",
      "10": "32",
      "11": "31",
      "12": "28",
      "13": "25",
      "14": "35",
      "15": "33",
      "16": "33",
      "17": "28",
      "18": "24",
      "19": "29",
      "20": "30",
      "21": "31",
      "22": "29",
      "23": "35",
      "24": "34",
      "25": "28",
      "26": "28",
      "27": "27",
      "28": "28",
      "29": "27",
      "30": "33",
      "31": "31",
    },
    Ecclesiastes: {
      "1": "18",
      "2": "26",
      "3": "22",
      "4": "16",
      "5": "20",
      "6": "12",
      "7": "29",
      "8": "17",
      "9": "18",
      "10": "20",
      "11": "10",
      "12": "14",
    },
    "Song of Solomon": {
      "1": "17",
      "2": "17",
      "3": "11",
      "4": "16",
      "5": "16",
      "6": "13",
      "7": "13",
      "8": "14",
    },
    Isaiah: {
      "1": "31",
      "2": "22",
      "3": "26",
      "4": "6",
      "5": "30",
      "6": "13",
      "7": "25",
      "8": "22",
      "9": "21",
      "10": "34",
      "11": "16",
      "12": "6",
      "13": "22",
      "14": "32",
      "15": "9",
      "16": "14",
      "17": "14",
      "18": "7",
      "19": "25",
      "20": "6",
      "21": "17",
      "22": "25",
      "23": "18",
      "24": "23",
      "25": "12",
      "26": "21",
      "27": "13",
      "28": "29",
      "29": "24",
      "30": "33",
      "31": "9",
      "32": "20",
      "33": "24",
      "34": "17",
      "35": "10",
      "36": "22",
      "37": "38",
      "38": "22",
      "39": "8",
      "40": "31",
      "41": "29",
      "42": "25",
      "43": "28",
      "44": "28",
      "45": "25",
      "46": "13",
      "47": "15",
      "48": "22",
      "49": "26",
      "50": "11",
      "51": "23",
      "52": "15",
      "53": "12",
      "54": "17",
      "55": "13",
      "56": "12",
      "57": "21",
      "58": "14",
      "59": "21",
      "60": "22",
      "61": "11",
      "62": "12",
      "63": "19",
      "64": "12",
      "65": "25",
      "66": "24",
    },
    Jeremiah: {
      "1": "19",
      "2": "37",
      "3": "25",
      "4": "31",
      "5": "31",
      "6": "30",
      "7": "34",
      "8": "22",
      "9": "26",
      "10": "25",
      "11": "23",
      "12": "17",
      "13": "27",
      "14": "22",
      "15": "21",
      "16": "21",
      "17": "27",
      "18": "23",
      "19": "15",
      "20": "18",
      "21": "14",
      "22": "30",
      "23": "40",
      "24": "10",
      "25": "38",
      "26": "24",
      "27": "22",
      "28": "17",
      "29": "32",
      "30": "24",
      "31": "40",
      "32": "44",
      "33": "26",
      "34": "22",
      "35": "19",
      "36": "32",
      "37": "21",
      "38": "28",
      "39": "18",
      "40": "16",
      "41": "18",
      "42": "22",
      "43": "13",
      "44": "30",
      "45": "5",
      "46": "28",
      "47": "7",
      "48": "47",
      "49": "39",
      "50": "46",
      "51": "64",
      "52": "34",
    },
    Lamentations: {
      "1": "22",
      "2": "22",
      "3": "66",
      "4": "22",
      "5": "22",
    },
    Ezekiel: {
      "1": "28",
      "2": "10",
      "3": "27",
      "4": "17",
      "5": "17",
      "6": "14",
      "7": "27",
      "8": "18",
      "9": "11",
      "10": "22",
      "11": "25",
      "12": "28",
      "13": "23",
      "14": "23",
      "15": "8",
      "16": "63",
      "17": "24",
      "18": "32",
      "19": "14",
      "20": "49",
      "21": "32",
      "22": "31",
      "23": "49",
      "24": "27",
      "25": "17",
      "26": "21",
      "27": "36",
      "28": "26",
      "29": "21",
      "30": "26",
      "31": "18",
      "32": "32",
      "33": "33",
      "34": "31",
      "35": "15",
      "36": "38",
      "37": "28",
      "38": "23",
      "39": "29",
      "40": "49",
      "41": "26",
      "42": "20",
      "43": "27",
      "44": "31",
      "45": "25",
      "46": "24",
      "47": "23",
      "48": "35",
    },
    Daniel: {
      "1": "21",
      "2": "49",
      "3": "30",
      "4": "37",
      "5": "31",
      "6": "28",
      "7": "28",
      "8": "27",
      "9": "27",
      "10": "21",
      "11": "45",
      "12": "13",
    },
    Hosea: {
      "1": "11",
      "2": "23",
      "3": "5",
      "4": "19",
      "5": "15",
      "6": "11",
      "7": "16",
      "8": "14",
      "9": "17",
      "10": "15",
      "11": "12",
      "12": "14",
      "13": "16",
      "14": "9",
    },
    Joel: {
      "1": "20",
      "2": "32",
      "3": "21",
    },
    Amos: {
      "1": "15",
      "2": "16",
      "3": "15",
      "4": "13",
      "5": "27",
      "6": "14",
      "7": "17",
      "8": "14",
      "9": "15",
    },
    Obadiah: {
      "1": "21",
    },
    Jonah: {
      "1": "17",
      "2": "10",
      "3": "10",
      "4": "11",
    },
    Micah: {
      "1": "16",
      "2": "13",
      "3": "12",
      "4": "13",
      "5": "15",
      "6": "16",
      "7": "20",
    },
    Nahum: {
      "1": "15",
      "2": "13",
      "3": "19",
    },
    Habakkuk: {
      "1": "17",
      "2": "20",
      "3": "19",
    },
    Zephaniah: {
      "1": "18",
      "2": "15",
      "3": "20",
    },
    Haggai: {
      "1": "15",
      "2": "23",
    },
    Zechariah: {
      "1": "21",
      "2": "13",
      "3": "10",
      "4": "14",
      "5": "11",
      "6": "15",
      "7": "14",
      "8": "23",
      "9": "17",
      "10": "12",
      "11": "17",
      "12": "14",
      "13": "9",
      "14": "21",
    },
    Malachi: {
      "1": "14",
      "2": "17",
      "3": "18",
      "4": "6",
    },
    Matthew: {
      "1": "25",
      "2": "23",
      "3": "17",
      "4": "25",
      "5": "48",
      "6": "34",
      "7": "29",
      "8": "34",
      "9": "38",
      "10": "42",
      "11": "30",
      "12": "50",
      "13": "58",
      "14": "36",
      "15": "39",
      "16": "28",
      "17": "27",
      "18": "35",
      "19": "30",
      "20": "34",
      "21": "46",
      "22": "46",
      "23": "39",
      "24": "51",
      "25": "46",
      "26": "75",
      "27": "66",
      "28": "20",
    },
    Mark: {
      "1": "45",
      "2": "28",
      "3": "35",
      "4": "41",
      "5": "43",
      "6": "56",
      "7": "37",
      "8": "38",
      "9": "50",
      "10": "52",
      "11": "33",
      "12": "44",
      "13": "37",
      "14": "72",
      "15": "47",
      "16": "20",
    },
    Luke: {
      "1": "80",
      "2": "52",
      "3": "38",
      "4": "44",
      "5": "39",
      "6": "49",
      "7": "50",
      "8": "56",
      "9": "62",
      "10": "42",
      "11": "54",
      "12": "59",
      "13": "35",
      "14": "35",
      "15": "32",
      "16": "31",
      "17": "37",
      "18": "43",
      "19": "48",
      "20": "47",
      "21": "38",
      "22": "71",
      "23": "56",
      "24": "53",
    },
    John: {
      "1": "51",
      "2": "25",
      "3": "36",
      "4": "54",
      "5": "47",
      "6": "71",
      "7": "53",
      "8": "59",
      "9": "41",
      "10": "42",
      "11": "57",
      "12": "50",
      "13": "38",
      "14": "31",
      "15": "27",
      "16": "33",
      "17": "26",
      "18": "40",
      "19": "42",
      "20": "31",
      "21": "25",
    },
    Acts: {
      "1": "26",
      "2": "47",
      "3": "26",
      "4": "37",
      "5": "42",
      "6": "15",
      "7": "60",
      "8": "40",
      "9": "43",
      "10": "48",
      "11": "30",
      "12": "25",
      "13": "52",
      "14": "28",
      "15": "41",
      "16": "40",
      "17": "34",
      "18": "28",
      "19": "41",
      "20": "38",
      "21": "40",
      "22": "30",
      "23": "35",
      "24": "27",
      "25": "27",
      "26": "32",
      "27": "44",
      "28": "31",
    },
    Romans: {
      "1": "32",
      "2": "29",
      "3": "31",
      "4": "25",
      "5": "21",
      "6": "23",
      "7": "25",
      "8": "39",
      "9": "33",
      "10": "21",
      "11": "36",
      "12": "21",
      "13": "14",
      "14": "23",
      "15": "33",
      "16": "27",
    },
    "1 Corinthians": {
      "1": "31",
      "2": "16",
      "3": "23",
      "4": "21",
      "5": "13",
      "6": "20",
      "7": "40",
      "8": "13",
      "9": "27",
      "10": "33",
      "11": "34",
      "12": "31",
      "13": "13",
      "14": "40",
      "15": "58",
      "16": "24",
    },
    "2 Corinthians": {
      "1": "24",
      "2": "17",
      "3": "18",
      "4": "18",
      "5": "21",
      "6": "18",
      "7": "16",
      "8": "24",
      "9": "15",
      "10": "18",
      "11": "33",
      "12": "21",
      "13": "14",
    },
    Galatians: {
      "1": "24",
      "2": "21",
      "3": "29",
      "4": "31",
      "5": "26",
      "6": "18",
    },
    Ephesians: {
      "1": "23",
      "2": "22",
      "3": "21",
      "4": "32",
      "5": "33",
      "6": "24",
    },
    Philippians: {
      "1": "30",
      "2": "30",
      "3": "21",
      "4": "23",
    },
    Colossians: {
      "1": "29",
      "2": "23",
      "3": "25",
      "4": "18",
    },
    "1 Thessalonians": {
      "1": "10",
      "2": "20",
      "3": "13",
      "4": "18",
      "5": "28",
    },
    "2 Thessalonians": {
      "1": "12",
      "2": "17",
      "3": "18",
    },
    "1 Timothy": {
      "1": "20",
      "2": "15",
      "3": "16",
      "4": "16",
      "5": "25",
      "6": "21",
    },
    "2 Timothy": {
      "1": "18",
      "2": "26",
      "3": "17",
      "4": "22",
    },
    Titus: {
      "1": "16",
      "2": "15",
      "3": "15",
    },
    Philemon: {
      "1": "25",
    },
    Hebrews: {
      "1": "14",
      "2": "18",
      "3": "19",
      "4": "16",
      "5": "14",
      "6": "20",
      "7": "28",
      "8": "13",
      "9": "28",
      "10": "39",
      "11": "40",
      "12": "29",
      "13": "25",
    },
    James: {
      "1": "27",
      "2": "26",
      "3": "18",
      "4": "17",
      "5": "20",
    },
    "1 Peter": {
      "1": "25",
      "2": "25",
      "3": "22",
      "4": "19",
      "5": "14",
    },
    "2 Peter": {
      "1": "21",
      "2": "22",
      "3": "18",
    },
    "1 John": {
      "1": "10",
      "2": "29",
      "3": "24",
      "4": "21",
      "5": "21",
    },
    "2 John": {
      "1": "13",
    },
    "3 John": {
      "1": "15",
    },
    Jude: {
      "1": "25",
    },
    Revelation: {
      "1": "20",
      "2": "29",
      "3": "22",
      "4": "11",
      "5": "14",
      "6": "17",
      "7": "17",
      "8": "13",
      "9": "21",
      "10": "11",
      "11": "19",
      "12": "17",
      "13": "18",
      "14": "20",
      "15": "8",
      "16": "21",
      "17": "18",
      "18": "24",
      "19": "21",
      "20": "15",
      "21": "27",
      "22": "21",
    },
  };

  // Function to do first check if bible format is valid
  function isReferenceFormatValid(reference) {
    // doesn't start with either two letters or a digit followed by a space, lack at least one letter, space, or period after the initial characters, or if it doesn't end with a digit followed by any combination of spaces, numbers, hyphens, and colons.
    if (!/^(?:[a-zA-Z]{2}|[0-9]\s)[a-zA-Z\s.]+[\d\s:-]+$/.test(reference)) {
      console.log(
        "doesn't start with either two letters or a digit followed by a space, lack at least one letter, space, or period after the initial characters, or if it doesn't end with a digit followed by any combination of spaces, numbers, hyphens, and colons."
      );
      return false;
    }

    // Fail if two special characters appear right after each other with no characters or only whitespaces between them
    if (/(?:[^\w\s]|^)\s*[\W_]+\s*(?:[^\w\s]|$)/.test(reference)) {
      console.log(
        "Fail: Two special characters detected with no characters or only whitespaces between them."
      );
      return false;
    }

    // Fail if there are more than 2 colons, more than one hyphen, or more than one period
    if (
      (reference.match(/:/g) || []).length > 2 ||
      (reference.match(/-/g) || []).length > 1 ||
      (reference.match(/\./g) || []).length > 1
    ) {
      console.log(
        "Fail: More than 2 colons, more than one hyphen, or more than one period detected."
      );
      return false;
    }

    // Fail if there is a special character other than periods, hyphens, or colons
    if (/[^a-zA-Z0-9\s\-\.:]/.test(reference)) {
      console.log("Fail: Special character other than periods, hyphens, or colons detected.");
      return false;
    }

    // Fail if it begins or ends with a special character
    if (/^[\-:.\s]/.test(reference.trim()) || /[\-:.\s]$/.test(reference.trim())) {
      console.log("Fail: Begins or ends with a special character.");
      return false;
    }

    const regexPattern =
      /(?<Book>[a-zA-Z0-9. ]+?)\s*(?:(?<StartChapter>\d+)\s*(?::\s*(?<StartVerse>\d+)\s*)?(?:-\s*(?:(?<EndChapter>\d+)\s*:)?(?<EndVerse>\d+)\s*)?)?$/;

    const match = reference.match(regexPattern);

    if (match) {
      const groups = match.groups;

      // Ensure at least a chapter is present for it to be a valid reference
      if (groups.StartChapter) {
        return true;
      }
    }

    console.log("Fail: Reference format is invalid.");
    return false;
  }

  // Function to parse the book from a Bible reference
  function parseBookFromNumericRange(reference): { book: string; numericRef: string } | false {
    // Replace 2 or more white spaces with a single white space
    // Remove special characters other than spaces, colons, and hyphens
    let cleanedReference = reference
      .replace(/\s{2,}/g, " ")
      .replace(/[^a-zA-Z0-9\s:-]/g, "")
      .trim()
      .toLowerCase();

    let book = null;
    let numericRef = null;
    let longestMatchLength = 0;

    // Iterate through each book and its aliases to find the longest match
    for (const [bookName, aliases] of Object.entries(bookAliases)) {
      aliases.push(bookName); // Include the actual book name in the search

      for (const alias of aliases) {
        const lowerAlias = alias.toLowerCase(); // Convert alias to lowercase
        const aliasLength = lowerAlias.length;
        if (
          cleanedReference.startsWith(lowerAlias) &&
          (cleanedReference[aliasLength] === " " || cleanedReference[aliasLength] === ":") &&
          aliasLength > longestMatchLength
        ) {
          longestMatchLength = aliasLength;
          book = bookName;
          numericRef = cleanedReference.substring(aliasLength).trim().replace(/\s/g, ""); // Use the original reference for the numericRef part, but trim it
        }
      }
    }

    // If a valid book is found, return it along with the numericRef characters
    if (book && numericRef !== null) {
      return { book, numericRef };
    } else {
      return false;
    }
  }

  function parseNumericRange(reference) {
    // Initialize the object to store structured data
    const structuredData = {
      full_reference: reference,
      StartChapter: null,
      StartVerse: null,
      EndChapter: null,
      EndVerse: null,
    };

    // Case: Single chapter (e.g., "1")
    if (!reference.includes("-") && !reference.includes(":")) {
      structuredData.StartChapter = reference;
      return structuredData;
    }

    // Case: Range of chapters (e.g., "1-3")
    if (reference.includes("-") && !reference.includes(":")) {
      const [startChapter, endChapter] = reference.split("-");
      structuredData.StartChapter = startChapter;
      structuredData.EndChapter = endChapter;
      return structuredData;
    }

    // Case: Single chapter with range of verses (e.g., "1:2-4")
    if (
      reference.includes("-") &&
      reference.includes(":") &&
      (reference.match(/-/g) || []).length === 1 &&
      (reference.match(/:/g) || []).length === 1
    ) {
      const [startChapter, verseRange] = reference.split(":");
      const [startVerse, endVerse] = verseRange.split("-");
      structuredData.StartChapter = startChapter;
      structuredData.StartVerse = startVerse;
      structuredData.EndVerse = endVerse;
      return structuredData;
    }

    // Case: Range of chapters and verses (e.g., "1:2-3:4")
    if (
      reference.includes("-") &&
      reference.includes(":") &&
      (reference.match(/-/g) || []).length === 1 &&
      (reference.match(/:/g) || []).length === 2
    ) {
      const [startRef, endRef] = reference.split("-");
      const [startChapter, startVerse] = startRef.split(":");
      const [endChapter, endVerse] = endRef.split(":");
      structuredData.StartChapter = startChapter;
      structuredData.StartVerse = startVerse;
      structuredData.EndChapter = endChapter;
      structuredData.EndVerse = endVerse;
      return structuredData;
    }

    // Case: Single chapter with a single verse (e.g., "1:1")
    if (
      !reference.includes("-") &&
      reference.includes(":") &&
      (reference.match(/:/g) || []).length === 1
    ) {
      const [startChapter, startVerse] = reference.split(":");
      structuredData.StartChapter = startChapter;
      structuredData.StartVerse = startVerse;
      return structuredData;
    }

    // If none of the above cases apply, return an error message
    return false;
  }

  function isNumericRangeValid(structuredData, book) {
    const { full_reference, StartChapter, StartVerse, EndChapter, EndVerse } = structuredData;

    // Check if the start chapter or verse is zero
    if (parseInt(StartChapter, 10) === 0 || (StartVerse && parseInt(StartVerse, 10) === 0)) {
      console.log("Start chapter or verse should not be zero.");
      return false;
    }

    // Check if the end chapter or verse is zero, if applicable
    if (
      (EndChapter && parseInt(EndChapter, 10) === 0) ||
      (EndVerse && parseInt(EndVerse, 10) === 0)
    ) {
      console.log("End chapter or verse should not be zero.");
      return false;
    }

    // Check if the start chapter is a valid integer
    if (!Number.isInteger(parseInt(StartChapter, 10))) {
      console.log("Start chapter is not a valid integer.");
      return false;
    }

    // Check if the end chapter is a valid integer, if applicable
    if (EndChapter && !Number.isInteger(parseInt(EndChapter, 10))) {
      console.log("End chapter is not a valid integer.");
      return false;
    }

    // Check if the start chapter exists in the given book
    if (
      !bibleStructure.hasOwnProperty(book) ||
      !bibleStructure[book].hasOwnProperty(StartChapter)
    ) {
      console.log(`Start chapter does not exist in the book ${book}.`);
      return false;
    }

    // Check if the end chapter exists in the given book, if applicable
    if (
      EndChapter &&
      (!bibleStructure.hasOwnProperty(book) || !bibleStructure[book].hasOwnProperty(EndChapter))
    ) {
      console.log(`End chapter does not exist in the book ${book}.`);
      return false;
    }

    // Check if the start chapter is less than or equal to the end chapter, if both are defined
    if (EndChapter && parseInt(StartChapter, 10) > parseInt(EndChapter, 10)) {
      console.log("Start chapter is greater than the end chapter.");
      return false;
    }

    // Verse validations

    // Check if the start verse is a valid integer
    if (StartVerse && !Number.isInteger(parseInt(StartVerse, 10))) {
      console.log("Start verse is not a valid integer.");
      return false;
    }

    // Check if the end verse is a valid integer, if applicable
    if (EndVerse && !Number.isInteger(parseInt(EndVerse, 10))) {
      console.log("End verse is not a valid integer.");
      return false;
    }

    // Check if the start verse exists in the given chapter, if applicable
    if (parseInt(StartVerse, 10) > parseInt(bibleStructure[book][StartChapter], 10)) {
      console.log(`Start verse does not exist in chapter ${StartChapter} of the book ${book}.`);
      return false;
    }

    // Check if the end verse exists in the given chapter, if applicable
    if (
      EndVerse &&
      parseInt(EndVerse, 10) > parseInt(bibleStructure[book][EndChapter || StartChapter], 10)
    ) {
      console.log(
        `End verse does not exist in chapter ${EndChapter || StartChapter} of the book ${book}.`
      );
      return false;
    }

    // Check if the start verse is less than or equal to the end verse when the start and end chapters are the same
    if (
      (StartChapter === EndChapter || !EndChapter) &&
      parseInt(StartVerse, 10) >= parseInt(EndVerse, 10)
    ) {
      console.log("Start verse is greater than or equal to the end verse in the same chapter.");
      return false;
    }

    return true;
  }

  // Define the function to fetch the Bible passage
  async function fetchBiblePassage(query) {
    // Define API endpoint and headers
    const url = `https://api.esv.org/v3/passage/text/?q=${encodeURIComponent(
      query
    )}&include-passage-references=false&include-verse-numbers=true&include-footnotes=false&include-footnote-body=false&include-headings=false&include-short-copyright=false&include-copyright=false&indent-paragraphs=0&indent-poetry=false&line-length=0`;
    const headers = new Headers({
      Authorization: "Token b97f811347c70fe6b73218d4d51ac3d25592a2c7",
    });

    try {
      // Make the API request
      const response = await fetch(url, { method: "GET", headers: headers });

      // Check if the request was successful
      if (response.ok) {
        const data = await response.json();
        // console.log("Received data:", data);
        return data;
      } else {
        console.log("Failed to fetch Bible passage:", response.statusText);
        return null;
      }
    } catch (error) {
      console.log("An error occurred:", error);
      return null;
    }
  }
  //return fail if something isn't accecptable
  if (!isReferenceFormatValid(reference)) {
    console.log("isReferenceFormatValid failed");
    return false;
  }
  if (!parseBookFromNumericRange(reference)) {
    console.log("parseBookFromNumericRange failed");
    return false;
  }
  return new Promise((resolve, reject) => {
    if (parseBookFromNumericRange(reference) !== false) {
      const { book, numericRef } = parseBookFromNumericRange(reference) as {
        book: string;
        numericRef: string;
      };
      if (!parseNumericRange(numericRef)) {
        console.log("parseNumericRange failed");
        return false;
      }
      if (!isNumericRangeValid(parseNumericRange(numericRef), book)) {
        console.log("parseNumericRange failed");
        return false;
      }

      fetchBiblePassage(book + " " + numericRef).then((data) => {
        if (data) {
          console.log("Passage:", data.passages[0]);
          resolve(data.passages[0].replace(/\s+/g, " ").replace(/\n+/g, ""));
        } else {
          reject(false);
        }
      });
    } else {
      reject(false);
    }
  });
}
