name: CI

on:
  push:
    branches:
      - production
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - name: build and deploy
        run: |
          cd ops
          echo $SECRETS_FILE > secrets.json
          export SECRETS_FILE_LOC=$(pwd)/secrets.json
          nix run
        env:
          SECRETS_FILE: ${{secrets.SECRETS_FILE}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          SERVER_IP: ${{secrets.SERVER_IP}}

